# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        /:year-:month-:day-:title/
# relative_permalinks: true

# Setup
title:            Blog HR
tagline:          'A Jekyll theme'
description:      '이것저것'

#'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'HR Lee'
  url:            /

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           /

plugins: [jekyll-paginate, jekyll-gist]

collections:
  categories:
    output: true
    sort_by: order

default:
  -
    scope:
      path: ''
      type: categories
    value:
      layout: page
      dynamic_title: true